#!/bin/bash

#EJERCICIO PARA COMPARAR SECUENCIA DE PROTEINA DE HUMANO CONTRA BASE DE DATOS DE ZEBRAFISH 

#DIRECCION A DIRECTORIO DE TRABAJO
cd /home/zbluze/Desktop/TAREA_4


#INSTALACIÓN DE BIOCONTAINERS CON BLAST
docker pull biocontainers/blast


#BAJANDO SECUENCIA DE PROTEINA PRION DE HUMANO
wget http://www.uniprot.org/uniprot/P04156.fasta


#BAJANDO BASE DE DATOS DE ZEBRAFISH
curl -O ftp://ftp.ncbi.nih.gov/refseq/D_rerio/mRNA_Prot/zebrafish.1.protein.faa.gz


#DESCOMPRIMIENDO BASE DE DATOS DE ZEBRAFISH
gunzip zebrafish.1.protein.faa.gz


#PREPARACION BASE DE DATOS DE ZEBRAFISH
docker run -v /home/zbluze/Desktop/TAREA_4:/data/ biocontainers/blast makeblastdb -in zebrafish.1.protein.faa -dbtype prot


#ALINEAMIENTO BASE DE DATOS DE ZEBRAFISH CONTRA PROTEINA PRION DE HUMANO
docker run -v /home/zbluze/Desktop/TAREA_4:/data/ biocontainers/blast blastp -query P04156.fasta -db zebrafish.1.protein.faa -out results.txt